language: php 

os:
  - linux
  - osx

sudo: false

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
      dist: trusty

install:
  - travis_retry composer install --no-interaction --no-suggest

script: ./vendor/bin/phpunit
